### 회원가입
POST http://localhost:8888/auth/signUp
Content-Type: application/json

{
  "name" : "금강선",
  "email" : "aaa@ccc",
  "password" : "1234"
}

### 회원가입 2
POST http://localhost:8888/auth/signUp
Content-Type: application/json

{
"name" : "은강선",
"email" : "bbb@ccc",
"password" : "1234"
}


### 로그인 - form 방식

POST http://localhost:8888/auth/login
Content-Type: application/x-www-form-urlencoded

username=aaa@ccc&password=1234&remember=1

### 로그인 - json 방식
POST http://localhost:8888/auth/login
content-Type: application/json

{
  "email": "aaa@ccc",
  "password": "1234"
}

### 로그인2 - json 방식
POST http://localhost:8888/auth/login
content-Type: application/json

{
  "email": "bbb@ccc",
  "password": "1234"
}

### 메인 페이지
GET http://localhost:8888

### 사용자 페이지
GET http://localhost:8888/user

### 관리자 페이지
GET http://localhost:8888/admin




### 인증 페이지 요청

GET http://localhost:8888/foo
Content-Type: application/json
Cookie: SESSION=d6edbaed-7e78-407d-83e3-d08e2c41d0a5